### ISSUE TITLE
ErrorException in GET /

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Website#5]
## New exception in Asgardcms.com

**ErrorException** in **GET /**
Array to string conversion

[View on Bugsnag](https://bugsnag.com/nwidart/asgardcms-dot-com/errors/5545530e22dbb1898352c367?event_id=5545530f5d186b5a23ef24e9)

## Stacktrace

    Modules/Menu/Repositories/Cache/CacheMenuDecorator.php:28 - handleError
    Modules/Menu/Repositories/Cache/CacheMenuDecorator.php:28 - allOnline
    Modules/Menu/Providers/MenuServiceProvider.php:154 - registerMenus

[View full stacktrace](https://bugsnag.com/nwidart/asgardcms-dot-com/errors/5545530e22dbb1898352c367?event_id=5545530f5d186b5a23ef24e9)

**Comment by joshbrw** [comment]
Automatic BugSnag issue, no longer occurs, closing issue.
